version: 2

project_name: goreleaser-ls

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/goreleaser-ls
    id: goreleaser
    binary: goreleaser-ls
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - goreleaser
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  extra_files:
    - glob: vscode-goreleaser-ls/*.vsix
